# Linear Regression (Closed Form)


引入必要包：numpy

In [1]:
import numpy as np

由于没有数据集，我们可以生成一些数据集，先定义一个线性函数，然后生成一些数据点，最后用线性回归拟合这些数据点。

In [2]:
target_w = np.array([12, 3, 17, 19])
x_0 = np.array([1])

w_dim = target_w.shape[0]
x_dim = w_dim - 1

def h(w, x):
    x = np.concatenate([x_0, x])
    return np.dot(w, x)

def f(x):
    return h(target_w, x)

In [3]:
f(np.array([2, 3, 4]))

145

In [4]:
def predict_arr(w, X):
    return np.array([h(w, x) for x in X])

In [5]:
# 生成数据函数
def generate_date(n : int, x_size : int, scale = 100, noise = True):
    X = np.random.rand(n, x_size)
    X *= scale # scale up
    Y = predict_arr(target_w, X)
    if noise:
        epsilon = np.random.normal(loc=0.0, scale=1.0, size=(n))
        Y = Y + epsilon
    return X, Y

In [6]:
N_D = 100 # 数据集有多大
X, Y = generate_date(N_D, x_dim, True)
print(X)
print(Y)

[[4.02754209e-01 5.85527163e-01 6.41857798e-01]
 [7.26396363e-01 1.22817984e-01 3.18482709e-03]
 [3.52900714e-01 8.00647143e-01 3.67622872e-01]
 [6.01854886e-02 4.90429126e-01 5.02710673e-01]
 [7.06108015e-01 6.26485027e-01 8.55562545e-01]
 [9.27145806e-02 7.24909038e-01 8.93330381e-01]
 [2.65792406e-01 9.04506069e-01 4.53009103e-02]
 [5.92387000e-01 5.69194101e-01 3.29720127e-01]
 [6.28694958e-01 4.69484736e-02 2.63034588e-01]
 [5.69884119e-01 8.19996316e-01 5.46372598e-01]
 [8.36982255e-01 5.69609555e-01 7.71891920e-01]
 [5.72273303e-01 8.39325421e-01 9.79605678e-03]
 [2.35569385e-01 3.29544350e-01 7.79158127e-01]
 [9.81326858e-01 6.94356797e-01 3.12854632e-01]
 [5.75873040e-01 3.36852134e-01 8.74608101e-01]
 [6.71490076e-01 8.39429054e-02 2.69979273e-01]
 [3.77697791e-01 9.22478276e-01 4.17373048e-02]
 [4.69647770e-01 6.47831863e-01 5.64753697e-01]
 [7.31435194e-01 2.88374318e-01 1.79529949e-01]
 [4.98387023e-01 1.40266351e-01 2.74098414e-03]
 [7.05966219e-01 1.81935571e-01 1.355595

$$
L(y, \hat{y}) = \frac{1}{n}\sum_{i=1}^{n}(y_i - \mathbf{w}^T\mathbf{x})^2
$$

In [7]:
def loss(w, X, Y):
    Y_hat = predict_arr(w, X)
    delta = (Y - Y_hat) ** 2
    return np.mean(delta)


In [8]:
w = np.random.rand(w_dim)
print("rand_w:", w)
print("loss  :", loss(w, X, Y))

rand_w: [0.41706846 0.92453563 0.23560294 0.64782663]
loss  : 942.3344773320024


$$
\begin{align}
\mathbf{w}
&=\frac{\sum_{i=1}^{n}(\mathbf{x}_iy_i)}{\sum_{i=1}^{n}(\mathbf{x}_i^2)}\\
&= \frac{X\mathbf{y}}{{X^TX}}\\
&= (X^TX)^{-1}X \mathbf{y}
\end{align}
$$

In [9]:
def close_form(X, Y):
    ones_column = np.ones((X.shape[0], 1))
    X = np.hstack((ones_column, X))
    
    X_transpose = X.T
    X_transpose_X = np.dot(X_transpose, X)
    X_transpose_X_inv = np.linalg.inv(X_transpose_X)
    X_transpose_Y = np.dot(X_transpose, Y)
    
    w = np.dot(X_transpose_X_inv, X_transpose_Y)
    return w

w = close_form(X, Y)
print(w)

[12.65208767  2.76124229 16.55249252 18.2475405 ]


In [10]:
w = close_form(X, Y)
print(w)

[12.65208767  2.76124229 16.55249252 18.2475405 ]


In [11]:
loss(w, X, Y)

0.7735391305551191