# Linear Regression (Closed Form)


引入必要包：numpy

In [1]:
import numpy as np

由于没有数据集，我们可以生成一些数据集，先定义一个线性函数，然后生成一些数据点，最后用线性回归拟合这些数据点。

In [2]:
target_w = np.array([12, 3, 17, 19])
x_0 = np.array([1])

w_dim = target_w.shape[0]
x_dim = w_dim - 1

def h(w, x):
    x = np.concatenate([x_0, x])
    return np.dot(w, x)

def f(x):
    return h(target_w, x)

In [3]:
f(np.array([2, 3, 4]))

145

In [4]:
def predict_arr(w, X):
    return np.array([h(w, x) for x in X])

In [5]:
# 生成数据函数
def generate_date(n : int, x_size : int, noise = True):
    X = np.random.rand(n, x_size)
    X *= 100 # scale up
    Y = predict_arr(target_w, X)
    if noise:
        epsilon = np.random.normal(loc=0.0, scale=1.0, size=(n))
        Y = Y + epsilon
    return X, Y

In [6]:
N_D = 1000 # 数据集有多大
X, Y = generate_date(N_D, x_dim, True)
print(X)
print(Y)

[[82.30605078 99.88948429 78.3976414 ]
 [35.64287521 97.72299745 40.94619663]
 [ 1.88127459 90.26327519 43.66856947]
 ...
 [62.93925632 65.96531947 83.18906172]
 [47.93694799 54.70158188 44.49597855]
 [37.57612785 52.03795386 55.70130341]]
[3445.30684233 2557.25172274 2382.04482282  459.52081862 1391.32207127
 2818.5035403  2906.89450934 1964.74424244  748.53112762 1633.13749452
 1216.86571648 1146.58307895 2588.17855194 1230.51091748 2288.37587693
 1796.69887693 2127.50902472 1529.38418773 2480.97467225 1492.34942697
 3176.47578501 2760.65649555 1922.85700493 1088.05092702 1694.67789707
 2327.54513288 1023.68085259 2010.21270346 2200.71652668  680.53399685
 3384.36191554 1447.00486259 1440.29414306  698.24745574 1062.23046413
 2137.08959655 3176.7615474  1434.93703892 1684.6398352  2035.43781272
 1416.69453128  616.99002161 1456.36327156 1422.43327002 2681.57464219
 1519.66554156 2780.29291143 2612.52084049  487.99689548 1701.39212888
 2224.56375023 1743.49684629  899.76428485 1973.45

$$
L(y, \hat{y}) = \frac{1}{n}\sum_{i=1}^{n}(y_i - \mathbf{w}^T\mathbf{x})^2
$$

In [7]:
def loss(w, X, Y):
    Y_hat = predict_arr(w, X)
    delta = (Y - Y_hat) ** 2
    return np.mean(delta)


In [8]:
w = np.random.rand(w_dim)
print("rand_w:", w)
print("loss  :", loss(w, X, Y))

rand_w: [0.14739376 0.01839194 0.74040853 0.62976761]
loss  : 4018069.8167787716


$$
\begin{align}
\mathbf{w}
&=\frac{\sum_{i=1}^{n}(\mathbf{x}_iy_i)}{\sum_{i=1}^{n}(\mathbf{x}_i^2)}\\
&= \frac{X\mathbf{y}}{{X^TX}}\\
&= (X^TX)^{-1}X \mathbf{y}
\end{align}
$$

In [9]:
def close_form(X, Y):
    ones_column = np.ones((X.shape[0], 1))
    X = np.hstack((ones_column, X))
    
    X_transpose = X.T
    X_transpose_X = np.dot(X_transpose, X)
    X_transpose_X_inv = np.linalg.inv(X_transpose_X)
    X_transpose_Y = np.dot(X_transpose, Y)
    
    w = np.dot(X_transpose_X_inv, X_transpose_Y)
    return w

w = close_form(X, Y)
print(w)

[11.90668923  2.99852985 17.00125058 19.00191034]


In [10]:
w = close_form(X, Y)
print(w)

[11.90668923  2.99852985 17.00125058 19.00191034]


In [11]:
loss(w, X, Y)

1.0616943007808064